name: MyWorkFlow
on:
  push:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
      - uses: actions/checkout@v5.0.0
        
      - name: Run
        run: dotnet run
