name: MyWorkFlow
on:
  push:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: step1
        run: echo "Hello, world!!"

      - name: step2
        run: dotnet --info
